name: growfood
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <=4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flashy_tab_bar2: ^0.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Logonotext.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/Logonotext.png"
    background_color: "#0xFFFFFF"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/Logonotext.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/Logonotext.png"



flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/image/



  fonts : 
  - family : Manrope
    fonts:
      - asset: assets/fonts/Manrope/Manrope-Regular.ttf
        weight: 400
      - asset: assets/fonts/Manrope/Manrope-Bold.ttf
        weight : 800
      - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
      - asset: assets/fonts/Manrope/Manrope-Light.ttf
      - asset: assets/fonts/Manrope/Manrope-Medium.ttf
        weight: 500
      - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
        weight : 600
